#!/bin/sh
# chkconfig: 2345 95 05
# description: Endeca Platform start-stop script

ENDECA_USER=vagrant

case "$1" in
    'start')

		if [ -f "/var/lock/subsys/endecacas" ]
		then
			echo "Endeca CAS already running"
			exit
		fi

        su $ENDECA_USER -c "/usr/local/endeca/CAS/11.1.0/bin/cas-service.sh & >> /home/vagrant/scripts/startup_shutdown.log 2>&1 &"
		touch /var/lock/subsys/endecacas
        ;;
    'stop')
        su $ENDECA_USER -c "/usr/local/endeca/CAS/11.1.0/bin/cas-service-shutdown.sh >> /home/vagrant/scripts/startup_shutdown.log 2>&1"
        rm -f /var/lock/subsys/endecacas
        ;;
esac